Use view binding in all views
rafsanjani/blizzard pull request #54
Opened 2020-10-15 18:35 UTC by lokaimoma

Got rid of kotlin synthetics and
find view by id.

2020-10-15 19:48 UTC, rafsanjani requested changes

2020-10-15 19:48 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/HomeFragment.kt
> +        binding.ivFavourite.setOnClickListener {
Use image prefix for `ImageViews` example. `imageFavorite`

2020-10-15 19:48 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/FavouritesFragment.kt
> -        rv_fav.layoutManager = layoutManager
use list prefix for recyclerviews accompanied by description in `camelCase`. example `listFavorites` instead of `rv_Fav`

2020-10-15 19:48 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/HomeFragment.kt
> +                val searchText = binding.etCityName.text.toString()
use `text` prefix for `EditTexts` example. `textCityName`

2020-10-15 19:48 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/extensions/FavouritesFragmentExtension.kt
> +            binding.ivNoData.visibility = View.INVISIBLE
When you have to call more than 2 methods or properties on the same object, try using one of the scoping functions. example
```
with(binding){
    imageNoData.visibility = INVISIBLE
    textLoaded.text.= "Loaded!"
}
```

instead of 
```
binding.imageNoData.visibility = INVISIBLE
binding.textLoaded = "Loaded!"
```

2020-10-15 19:51 UTC, lokaimoma commented
Thanks much i will make all the changes :handshake:

2020-10-16 08:51 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/util/FavouriteFragmentAdapter.kt
> +            tvCityName = itemView.findViewById(R.id.city_name)
Use `ViewBinding` in the adapters as well

2020-10-16 08:53 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/FavouritesFragment.kt
> +    var favouritesAdapter: FavouriteFragmentAdapter? = null
Make the adapter a non null type

2020-10-16 08:54 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/HomeFragment.kt
> +    val binding get() = homeBinding!!
I don't see the need for this property.

2020-10-16 08:56 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/extensions/HomeFragmentExtension.kt
>  fun HomeFragment.showViews() {
We will talk about this later

2020-10-16 08:57 UTC, rafsanjani commented on app/src/main/java/com/example/blizzard/views/extensions/HomeFragmentExtension.kt
> +    binding.btnCurrentLocation.apply {
I don't know if this binding object is nullable but if it is nullable then it's better to use a null safety on the expression. 
`binding?.btnCurrentLocation.apply{...}`

2020-10-16 08:58 UTC, rafsanjani commented on app/src/main/res/layout/fragment_favourites.xml
>          tools:listitem="@layout/weather_list_item" />
`RecyclerView` list items should be prefixed with `item` example. `item_weather.xml`

2020-10-16 09:00 UTC, rafsanjani requested changes
Almost there

2020-10-17 09:47 UTC, lokaimoma commented on app/src/main/java/com/example/blizzard/views/HomeFragment.kt
> +    val binding get() = homeBinding!!
Ohk will make the necessary changes

2020-10-17 11:18 UTC, lokaimoma commented on app/src/main/java/com/example/blizzard/views/extensions/HomeFragmentExtension.kt
> +    binding.btnCurrentLocation.apply {
it's not nullable, that i why introduced that property (val binding get() = homeBinding!!).

2020-10-17 11:23 UTC, lokaimoma commented on app/src/main/java/com/example/blizzard/views/extensions/HomeFragmentExtension.kt
> +    binding.btnCurrentLocation.apply {
I wanted to reduce the null safety calls

2020-10-17 13:57 UTC, merged